### ISSUE TITLE
Few minor issues

### ISSUE THREAD

**Issue by vr8hub** [mgbennet/frederick-douglass_narrative-of-the-life-of-frederick-douglass#1]
1. Both `semanticate` and `modernize-spelling` make changes that should be accepted.
2. The sections should be "non-fiction" rather than "non-fiction."
3. The unsemanticated `<i>`'s on his name change sound to me to be emphasis. ("I changed my name from _this_ to _that_.")
4. There are a few instances of commas inside closing parentheses, e.g. "(an aside,)"; those should be outside, e.g. "(an aside),". (I just had to change a bunch of these in the _Decameron_.)
5. The letter-left class isn't needed; just target the footer se.letter.dateline.
6. The `core.css` is not up-to-date with the latest tools. If you haven't already, you should upgrade the tools to their latest version. You can then do a dummy `se create-draft` and copy the `core.css` from that draft to your project.

This part is more subjective, so you have more leeway to ignore it. :)
In the long description's first paragraph's closing sentence, I think there's one too many "for"s. Either "the vivid language for which he was already known in his…" or "the vivid language he was already known for in his…".
The first sentence of the second paragraph is also a little clunky. Maybe "D's eloquence in his speeches caused some skeptics…" or something similar? 
There should be a comma after the "Thus" in the second sentence.

**Comment by mgbennet** [comment]
Thanks, Vince. I've addressed all these issues. I appreciate the help on the description, writing it is always the hardest part of a production for me. 

The only thing I'm not sure about is the change that `modernize-spelling` wants to make. The full quote is "They seldom come nearer to it than planting-time, harvest-time, cherry-time, spring-time, or fall-time." It wants to change "spring-time" to "springtime", which normally would be fine but in this case given that it's part of a list of hyphenated words, making one word unhyphenated would look strange. There was a similar issue in my previous production, and we agreed to keep the hyphen in to keep the pattern.

**Comment by vr8hub** [comment]
Ah, OK. In that case, I think that's a good call. I didn't look that closely at the surrounding material. I'm fine with leaving it.
